import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: { home: 'Home', about: 'About', methodology: 'Methodology', projects: 'Projects', skills: 'Skills', blog: 'Blog', personal: 'Personal', education: 'Education', contact: 'Contact' },
    hero: { greeting: "Hello, I'm", name: 'Sara', lastName: 'Soufi', roles: ['Full-Stack Developer', 'React Specialist', 'UI/UX Enthusiast'], bio: 'I design and develop modern, responsive web applications with a focus on clean code, exceptional user experiences, and cutting-edge technologies.', viewWork: 'View My Work', contactMe: 'Contact Me', scroll: 'Scroll' },
    about: { subtitle: 'Who Am I', title: 'About', description: "Currently pursuing my Master 1 in STIC, I am progressively developing skills in designing and developing web applications. My approach is based on clear methodology, a good understanding of user needs, and the application of modern web standards.", highlights: ['Web Development', 'UX/UI Design', 'Academic Projects', 'Continuous Learning'] },
    methodology: { subtitle: 'How I Work', title: 'Professional Workflow', description: 'A disciplined and results-driven workflow designed to transform complex ideas into reliable, high-quality digital solutions.', steps: [{ number: '01', title: 'Concept Framing', description: 'Clarifying the vision by translating initial ideas into well-defined objectives.', details: 'This stage establishes project boundaries, success criteria, and strategic priorities.' }, { number: '02', title: 'Strategic Exploration', description: 'Evaluating existing ecosystems, identifying opportunities, and assessing constraints.', details: 'Decisions are guided by data, feasibility, and long-term sustainability.' }, { number: '03', title: 'Experience Architecture', description: 'Structuring user journeys and visual systems with precision.', details: 'Interfaces are crafted to balance functionality, clarity, and aesthetic coherence.' }, { number: '04', title: 'Technical Execution', description: 'Engineering robust and maintainable solutions through clean architecture.', details: 'Focus is placed on reliability, scalability, and code quality.' }, { number: '05', title: 'Validation & Deployment', description: 'Ensuring readiness through testing, refinement, and controlled delivery.', details: 'The solution is optimized, validated, and prepared for real-world usage.' }] },
    projects: { subtitle: 'Portfolio', title: 'Academic Projects', description: 'Work completed as part of the Web Application Design module.', moreDetails: 'More Details', viewCode: 'View Code', detailedDescription: 'Detailed Description', objectives: 'Objectives', keyLearnings: 'Key Learnings', technologies: 'Technologies', items: [{ title: 'Introduction to Web', subtitle: 'Lab 1', description: 'Discovery of web development basics through HTML5 and CSS3, with emphasis on semantics, accessibility, and responsive design.', details: 'This lab introduced the foundational concepts of web development, focusing on creating semantic HTML structures and styling with CSS. We explored the importance of accessibility and responsive design principles.', objectivesList: ['Understand HTML5 semantic elements', 'Master CSS3 styling techniques', 'Implement responsive design patterns', 'Ensure web accessibility standards'], learningsList: ['Semantic HTML structure', 'CSS Flexbox and Grid layouts', 'Media queries for responsiveness', 'ARIA labels and accessibility'] }, { title: 'Modern JavaScript', subtitle: 'Lab 2', description: 'DOM manipulation, event handling, and use of ES6+ features.', details: 'This lab focused on modern JavaScript development, exploring ES6+ features and DOM manipulation techniques for creating interactive web applications.', objectivesList: ['Master ES6+ syntax and features', 'Understand DOM manipulation', 'Handle events effectively', 'Work with async operations'], learningsList: ['Arrow functions and destructuring', 'Event delegation patterns', 'Fetch API for HTTP requests', 'Promises and async/await'] }, { title: 'Node.js & NPM', subtitle: 'Lab 3', description: 'Setting up a backend environment with Node.js and introduction to Express.', details: 'This lab introduced server-side JavaScript development with Node.js, package management with NPM, and building APIs with Express framework.', objectivesList: ['Set up Node.js environment', 'Manage dependencies with NPM', 'Build REST APIs with Express', 'Understand middleware patterns'], learningsList: ['Node.js runtime environment', 'Package.json configuration', 'Express routing and middleware', 'HTTP request handling'] }] },
    skills: { subtitle: 'Expertise', title: 'Skills & Technologies', overview: 'Overview of my technical stack: web languages, frameworks and tools.', categories: { frontend: 'Front-end Web', backend: 'Back-end Web', mobile: 'Mobile App', tools: 'Tools & Technologies' } },
    blog: { subtitle: 'Insights', title: 'Blog & Articles', description: 'Short articles about my learning journey, challenges faced in projects, and solutions found.', readMore: 'Read More', articles: [{ title: 'My First Steps with React', date: 'Dec 2024', readTime: '5 min read', category: 'Learning', excerpt: 'Discovering React was a turning point in my web development journey. Here I share the challenges I faced and how I overcame them.' }, { title: 'Debugging Tips for Beginners', date: 'Nov 2024', readTime: '4 min read', category: 'Tips', excerpt: 'Debugging can be frustrating. Here are some techniques I learned that made my debugging process much more efficient.' }, { title: 'Understanding Responsive Design', date: 'Oct 2024', readTime: '6 min read', category: 'Tutorial', excerpt: 'Responsive design is essential in modern web development. Learn the key concepts and best practices I discovered.' }] },
    personal: { subtitle: 'Beyond Code', title: 'Personal Side', description: 'Discover who I am outside of coding - my hobbies, interests, and creative experiments.', hobbiesTitle: 'Hobbies & Interests', galleryTitle: 'Creative Experiments', funFact: 'Fun Fact', funFactText: 'I love experimenting with AI-generated art and exploring how technology can enhance creativity!', hobbies: [{ name: 'Reading', emoji: '📚', description: 'Tech books & novels' }, { name: 'Photography', emoji: '📷', description: 'Capturing moments' }, { name: 'Music', emoji: '🎵', description: 'Lo-fi & ambient' }, { name: 'Travel', emoji: '✈️', description: 'Exploring new places' }], gallery: [{ title: 'AI Art Exploration', emoji: '🎨', description: 'Experimenting with AI image generation tools' }, { title: 'UI Concepts', emoji: '💡', description: 'Creative interface design experiments' }, { title: 'Side Projects', emoji: '🚀', description: 'Personal coding experiments' }] },
    education: { subtitle: 'Academic Path', title: 'Education', current: 'Current Year', degree: 'Master 1 STIC', university: 'University', focus: 'Focus: Web Application Design & Development' },
    contact: { subtitle: 'Get In Touch', title: 'Contact', description: 'Open to internships, academic projects, and learning opportunities.', email: 'Email', location: 'Location', social: 'Social', form: { name: 'Name', email: 'Email', message: 'Message', send: 'Send Message' } },
    footer: { rights: 'All rights reserved.', madeWith: 'Made with' }
  },
  fr: {
    nav: { home: 'Accueil', about: 'À propos', methodology: 'Méthodologie', projects: 'Projets', skills: 'Compétences', blog: 'Blog', personal: 'Personnel', education: 'Formation', contact: 'Contact' },
    hero: { greeting: 'Bonjour, je suis', name: 'Sara', lastName: 'Soufi', roles: ['Développeuse Full-Stack', 'Spécialiste React', 'Passionnée UX/UI'], bio: "Je conçois et développe des applications web modernes et responsives, en mettant l'accent sur un code propre et des expériences utilisateur exceptionnelles.", viewWork: 'Voir mes travaux', contactMe: 'Me contacter', scroll: 'Défiler' },
    about: { subtitle: 'Qui suis-je', title: 'À propos', description: "Étudiante en Master 1 STIC, je développe progressivement des compétences en conception et développement d'applications web.", highlights: ['Développement Web', 'Design UX/UI', 'Projets Académiques', 'Apprentissage Continu'] },
    methodology: { subtitle: 'Ma méthode', title: 'Workflow Professionnel', description: 'Un flux de travail discipliné conçu pour transformer des idées complexes en solutions numériques fiables.', steps: [{ number: '01', title: 'Cadrage Conceptuel', description: 'Clarifier la vision en traduisant les idées initiales en objectifs bien définis.', details: 'Cette étape établit les limites du projet et les priorités stratégiques.' }, { number: '02', title: 'Exploration Stratégique', description: 'Évaluer les écosystèmes existants et identifier les opportunités.', details: 'Les décisions sont guidées par les données et la faisabilité.' }, { number: '03', title: "Architecture d'Expérience", description: 'Structurer les parcours utilisateurs et les systèmes visuels avec précision.', details: 'Les interfaces équilibrent fonctionnalité, clarté et cohérence esthétique.' }, { number: '04', title: 'Exécution Technique', description: 'Concevoir des solutions robustes grâce à une architecture propre.', details: "L'accent est mis sur la fiabilité et la qualité du code." }, { number: '05', title: 'Validation & Déploiement', description: 'Assurer la préparation par des tests et une livraison contrôlée.', details: 'La solution est optimisée et préparée pour une utilisation réelle.' }] },
    projects: { subtitle: 'Portfolio', title: 'Projets Académiques', description: "Travaux réalisés dans le cadre du module Conception d'Applications Web.", moreDetails: 'Plus de détails', viewCode: 'Voir le code', detailedDescription: 'Description détaillée', objectives: 'Objectifs', keyLearnings: 'Apprentissages clés', technologies: 'Technologies', items: [{ title: 'Introduction au Web', subtitle: 'Lab 1', description: "Découverte des bases du développement web à travers HTML5 et CSS3.", details: "Ce lab a introduit les concepts fondamentaux du développement web, en se concentrant sur la création de structures HTML sémantiques et le stylage avec CSS.", objectivesList: ['Comprendre les éléments HTML5 sémantiques', 'Maîtriser les techniques de stylage CSS3', 'Implémenter des patterns responsive', "Assurer les standards d'accessibilité"], learningsList: ['Structure HTML sémantique', 'Layouts CSS Flexbox et Grid', 'Media queries pour la responsivité', 'Labels ARIA et accessibilité'] }, { title: 'JavaScript Moderne', subtitle: 'Lab 2', description: 'Manipulation du DOM, gestion des événements et fonctionnalités ES6+.', details: "Ce lab s'est concentré sur le développement JavaScript moderne, explorant les fonctionnalités ES6+ et les techniques de manipulation du DOM.", objectivesList: ['Maîtriser la syntaxe ES6+', 'Comprendre la manipulation du DOM', 'Gérer les événements efficacement', 'Travailler avec les opérations async'], learningsList: ['Fonctions fléchées et déstructuration', 'Patterns de délégation d\'événements', 'API Fetch pour les requêtes HTTP', 'Promises et async/await'] }, { title: 'Node.js & NPM', subtitle: 'Lab 3', description: "Mise en place d'un environnement backend avec Node.js et introduction à Express.", details: "Ce lab a introduit le développement JavaScript côté serveur avec Node.js et la construction d'APIs avec Express.", objectivesList: ['Configurer l\'environnement Node.js', 'Gérer les dépendances avec NPM', 'Construire des APIs REST avec Express', 'Comprendre les patterns middleware'], learningsList: ['Environnement runtime Node.js', 'Configuration package.json', 'Routing et middleware Express', 'Gestion des requêtes HTTP'] }] },
    skills: { subtitle: 'Expertise', title: 'Compétences & Technologies', overview: 'Aperçu de ma stack technique : langages web, frameworks et outils.', categories: { frontend: 'Front-end Web', backend: 'Back-end Web', mobile: 'Application Mobile', tools: 'Outils & Technologies' } },
    blog: { subtitle: 'Insights', title: 'Blog & Articles', description: "Articles courts sur mon parcours d'apprentissage, les défis rencontrés et les solutions trouvées.", readMore: 'Lire plus', articles: [{ title: 'Mes premiers pas avec React', date: 'Déc 2024', readTime: '5 min', category: 'Apprentissage', excerpt: "Découvrir React a été un tournant dans mon parcours. Je partage ici les défis rencontrés et comment je les ai surmontés." }, { title: 'Conseils de débogage pour débutants', date: 'Nov 2024', readTime: '4 min', category: 'Conseils', excerpt: "Le débogage peut être frustrant. Voici des techniques qui ont rendu mon processus plus efficace." }, { title: 'Comprendre le design responsive', date: 'Oct 2024', readTime: '6 min', category: 'Tutoriel', excerpt: "Le design responsive est essentiel. Découvrez les concepts clés et bonnes pratiques." }] },
    personal: { subtitle: 'Au-delà du code', title: 'Côté Personnel', description: 'Découvrez qui je suis en dehors du code - mes hobbies, intérêts et expériences créatives.', hobbiesTitle: 'Hobbies & Intérêts', galleryTitle: 'Expériences Créatives', funFact: 'Fait amusant', funFactText: "J'adore expérimenter avec l'art généré par IA et explorer comment la technologie peut enrichir la créativité!", hobbies: [{ name: 'Lecture', emoji: '📚', description: 'Livres tech & romans' }, { name: 'Photographie', emoji: '📷', description: 'Capturer des moments' }, { name: 'Musique', emoji: '🎵', description: 'Lo-fi & ambient' }, { name: 'Voyage', emoji: '✈️', description: 'Explorer de nouveaux lieux' }], gallery: [{ title: 'Exploration Art IA', emoji: '🎨', description: "Expérimentation avec les outils de génération d'images IA" }, { title: 'Concepts UI', emoji: '💡', description: "Expériences de design d'interface créatif" }, { title: 'Projets Perso', emoji: '🚀', description: 'Expériences de code personnelles' }] },
    education: { subtitle: 'Parcours Académique', title: 'Formation', current: 'Année en cours', degree: 'Master 1 STIC', university: 'Université', focus: "Spécialisation : Conception et Développement d'Applications Web" },
    contact: { subtitle: 'Me contacter', title: 'Contact', description: "Ouverte aux stages, projets académiques et opportunités d'apprentissage.", email: 'Email', location: 'Localisation', social: 'Réseaux', form: { name: 'Nom', email: 'Email', message: 'Message', send: 'Envoyer' } },
    footer: { rights: 'Tous droits réservés.', madeWith: 'Fait avec' }
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const t = translations[language];
  const toggleLanguage = () => setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  return <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
